export const experience = [

  {
    company: "Dornach (ZieglerGroup)",
    position: "Full Stack Developer",
    timeline: "Oct 2023 - Oct 2024",
    tech: "TypeScript, Node.js, Vue.js, Sass, Socket.IO, MongoDB, Redis, Docker",
    desc: "Developing comprehensive web application that seamlessly integrates a variety of essential tools such as spreadsheets, maps, audio and video communication, forms, and more into a unified platform. This all-in-one solution also facilitates robust collaboration features tailored for businesses, enabling teams to work together efficiently and effectively within a single, organized environment",
    remote: true,
  },
  {
    company: "Apkeo",
    position: "Full Stack Developer",
    timeline: "Jul 2023 - Oct 2023",
    tech: "TypeScript, Node.js, Vue.js, Sass, Socket.IO, MongoDB, Redis, Docker",
    desc: "Developing comprehensive web application that seamlessly integrates a variety of essential tools such as spreadsheets, maps, audio and video communication, forms, and more into a unified platform. This all-in-one solution also facilitates robust collaboration features tailored for businesses, enabling teams to work together efficiently and effectively within a single, organized environment",
    remote: true,
  },
  {
    company: "WebWizards",
    position: "Frontend Developer",
    timeline: "Mar 2023 - Jul 2023",
    tech: "TypeScript, React.js, Vue.js, Next.js, Nuxt.js, Astro, TailwindCSS, Sass",
    desc: "Developing comprehensive web application that seamlessly integrates a variety of essential tools such as spreadsheets, maps, audio and video communication, forms, and more into a unified platform. This all-in-one solution also facilitates robust collaboration features tailored for businesses, enabling teams to work together efficiently and effectively within a single, organized environment",
    remote: true,
  },
  {
    company: "CodeClutch",
    position: "Full Stack Developer",
    timeline: "Oct 2022 - Feb 2023",
    tech: "TypeScript, Node.js, Nuxt.js, Pinia, TailwindCSS, MongoDB",
    desc: "Developing cutting-edge web application that serves as a centralized cryptocurrency trading platform. It unifies multiple digital asset exchanges into a single, user-friendly interface. Alongside essential trading tools, it incorporates advanced features including trading automation, enabling users to optimize their trading strategies",
    remote: true,
  },
  {
    company: "Freelance",
    position: "Full Stack Developer",
    timeline: "Oct 2022 - Feb 2023",
    tech: "TypeScript, Node.js, Nuxt.js, Pinia, TailwindCSS, MongoDB",
    desc: "Developing cutting-edge web application that serves as a centralized cryptocurrency trading platform. It unifies multiple digital asset exchanges into a single, user-friendly interface. Alongside essential trading tools, it incorporates advanced features including trading automation, enabling users to optimize their trading strategies",
    remote: true,
  },
  {
    company: "ATComputers",
    position: "Frontend Developer",
    timeline: "Dec 2019 - Apr 2021",
    tech: "Vue.js, Vuex, Sass, Python, Laravel",
    desc: "Working on customer relationship management (CRM) software. This software is designed to assist businesses in effectively managing and nurturing their relationships with customers, streamlining communication, tracking interactions, and enhancing overall customer satisfaction",
    remote: false,
  },
  {
    company: "Merito University",
    position: "Microsoft Helpdesk",
    timeline: "Oct 2021 - Feb 2024",
    tech: "",
    desc: "Providing assistance for MS365/Teams technical support hotline as well as supporting academic administration department helpline.",
    remote: true,
  },
];
